//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5483
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Egode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap closed {
            get {
                object obj = ResourceManager.GetObject("closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deal {
            get {
                object obj = ResourceManager.GetObject("deal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delivered {
            get {
                object obj = ResourceManager.GetObject("delivered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dhl {
            get {
                object obj = ResourceManager.GetObject("dhl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 啊a
        ///阿a
        ///呵a
        ///吖a
        ///嗄a
        ///腌a
        ///锕a
        ///爱ai
        ///矮ai
        ///挨ai
        ///哎ai
        ///碍ai
        ///癌ai
        ///艾ai
        ///唉ai
        ///哀ai
        ///蔼ai
        ///隘ai
        ///埃ai
        ///皑ai
        ///呆ai
        ///嗌ai
        ///嫒ai
        ///瑷ai
        ///暧ai
        ///捱ai
        ///砹ai
        ///嗳ai
        ///锿ai
        ///霭ai
        ///按an
        ///安an
        ///暗an
        ///岸an
        ///俺an
        ///案an
        ///鞍an
        ///氨an
        ///胺an
        ///厂an
        ///广an
        ///庵an
        ///揞an
        ///犴an
        ///铵an
        ///桉an
        ///谙an
        ///鹌an
        ///埯an
        ///黯an
        ///昂ang
        ///肮ang
        ///盎ang
        ///袄ao
        ///凹ao
        ///傲ao
        ///奥ao
        ///熬ao
        ///懊ao
        ///敖ao
        ///翱ao
        ///澳ao
        ///嚣ao
        ///拗ao
        ///媪ao
        ///廒ao
        ///骜ao
        ///嗷ao
        ///坳ao
        ///遨ao
        ///聱ao
        ///螯ao
        ///獒ao
        ///鏊ao
        ///鳌ao
        ///鏖ao
        ///岙ao
        ///把ba
        ///八ba
        ///吧ba
        ///爸ba
        ///拔ba
        ///罢ba
        ///跋ba
        ///巴ba
        ///芭ba
        ///扒ba
        ///坝ba
        ///霸ba
        ///叭ba
        ///靶ba
        ///笆ba
        ///疤ba
        ///耙ba
        ///捌ba
        ///粑ba
        ///茇ba
        ///岜ba
        ///鲅ba
        ///钯ba
        ///魃ba
        ///菝ba
        ///灞ba
        ///百 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hanzipinyin {
            get {
                return ResourceManager.GetString("hanzipinyin", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap localdhl {
            get {
                object obj = ResourceManager.GetObject("localdhl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap localnb {
            get {
                object obj = ResourceManager.GetObject("localnb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nb {
            get {
                object obj = ResourceManager.GetObject("nb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nb1 {
            get {
                object obj = ResourceManager.GetObject("nb1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paid {
            get {
                object obj = ResourceManager.GetObject("paid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap partialsent {
            get {
                object obj = ResourceManager.GetObject("partialsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sent {
            get {
                object obj = ResourceManager.GetObject("sent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sf_logo_new {
            get {
                object obj = ResourceManager.GetObject("sf_logo_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sf_logo_vertical {
            get {
                object obj = ResourceManager.GetObject("sf_logo_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tools_32x18 {
            get {
                object obj = ResourceManager.GetObject("tools_32x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tools_32x18_gray {
            get {
                object obj = ResourceManager.GetObject("tools_32x18_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yunda {
            get {
                object obj = ResourceManager.GetObject("yunda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yunda_32x18 {
            get {
                object obj = ResourceManager.GetObject("yunda_32x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yunda_32x18_gray {
            get {
                object obj = ResourceManager.GetObject("yunda_32x18_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yunda_32x181 {
            get {
                object obj = ResourceManager.GetObject("yunda_32x181", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zto_32x18 {
            get {
                object obj = ResourceManager.GetObject("zto_32x18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zto_32x18_gray {
            get {
                object obj = ResourceManager.GetObject("zto_32x18_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
